# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2e873b4e270c718ed31c8f423b8f91e957367be3dec328575947d7570fd0640385124f489473ab0f0d1d527e0e12f76cff2860db20f939601c16e3cd44565638

test:
  secret_key_base: ca0e5b317c10a3ca17848b9fdf248cb15e7b34031e77c8266cea2248f3a1e8db434a6d54c4bd7149362219264c10144eba51b8f59221eb9a8e440a991cd9a4d5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
